name: gwsnr
channels:
  - conda-forge
  - defaults
  - pip
dependencies:
  - python=3.10
  - pandoc
  - pip
  - pip:
    - html5lib==1.0b8  # Hack to ensure documentation generated
    - setuptools>=65.5.0
    - sphinx==7.2.6
    - nbsphinx==0.9.3
    - myst-parser==2.0.0
    - numpydoc==1.6.0
    - sphinx-tabs==3.4.1
    - sphinx-copybutton==0.5.2
    - sphinx-rtd-theme==1.3.0
    - autoapi==2.0.1
    - sphinx-autoapi==3.0.0
    - linkify-it-py
    - sphinx-jupyterbook-latex
    - gwsnr>=0.3.4

# to build the documentation, run:
# conda env create -f docs/requirements.yml
# to update the environment, run:
# conda env update -f docs/requirements.yml