name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run pytest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install .
        pip install pytest
        pip install ripplegw
        pip install jax
        pip install scikit-learn==1.7.1
        pip install tensorflow==2.17.1
        pip install tensorflow>=0.3.1
        
    - name: Run tests
      run: pytest -v -s
